### PR TITLE
Adding connectedToTheDom

### PR DESCRIPTION
**Pull request by fresheneesz**
I found another use case that was letting through backspace-related browser history state changes: If a backspace event results in removing the element being typed in from the dom, the default action ends up being a history change. So in the case a field has been removed from the dom, the default must also be prevented.

I also changed the validInputTypes to an object for performance and readability, and made a number of other minor readability improvements (including taking advantage of function hoisting).

### CODE REVIEW

**Comment by slorber** [comment]
Hi,

I'm not really sure to understand this usecase.
Do you mean that pressing "backspace" actually removes a text input from the dom? How can this happen? Isn't it only possible inside a contenteditable?

**Comment by fresheneesz** [comment]
"Do you mean that pressing "backspace" actually removes a text input from the dom?"

Yes. I have a situation where I have a list of text fields, and if I delete all the text inside one of those fields and press backspace again, it'll delete the whole field. Pressing enter creates a new field. Because of this, backspace-disabler doesn't currently prevent the default behavior because the input was done inside a text field, but the browser still triggers history changing behavior because the text field is no longer attached to the dom. This should be possible inside a contenteditable or a textfield/textarea.

**Comment by slorber** [comment]
> Yes. I have a situation where I have a list of text fields, and if I delete all the text inside one of those fields and press backspace again, it'll delete the whole field. Pressing enter creates a new field. 

Sorry but I don't understand this situation. In which situation pressing enter does a new "field" (btw what is a field? input?)

Can you reproduce this situation in a jsfiddle so that I can understand myself what is happening here? Are your fields inside a contenteditable or not? Also don't understand why you mention textarea as it's not supposed to contain childs as far as I know

**Comment by fresheneesz** [comment]
Yes it it a contenteditable. 

https://jsfiddle.net/663tr51z/

**Comment by fresheneesz** [comment]
Yes it is contenteditable.

https://jsfiddle.net/663tr51z/

**Comment by slorber** [comment]
sorry but I don't understand why you don't call preventDefault yourself?

```
if(event.keyCode === 8) {
     document.body.removeChild(a)
     event.preventDefault()
}
```

Once the input is removed, you won't go back no?

**Comment by fresheneesz** [comment]
"why you don't call preventDefault yourself?"

Why would I use backspace-disabler if I have to call preventDefault myself? Isn't the whole point _not_ having to worry about that?

**Comment by slorber** [comment]
hmmm I think I can see the problem.

Does does this implementation works for you? https://jsfiddle.net/663tr51z/11/

Honnestly I don't really understand your other changes like validInputTypes. Maybe these changes can be on another separate PR that we can discuss

**Comment by fresheneesz** [comment]
"I don't really understand your other changes like validInputTypes"

The validInputTypes change was for speed - checking an object for containing a key is much faster than `indexOf` on an array. The rest are simply changes for readability and don't affect either the logic or the performance. It unfortunate the diff can't show where code was moved, because there really weren't that many changes. I moved the exports to the top for readability, but it makes the diff hard to read.

**Comment by slorber** [comment]
> The validInputTypes change was for speed - checking an object for containing a key is much faster than indexOf on an array.

I understand that key hashing might give better perfs than large arrays, but do you have any benchmark for this kind of array size that using object is actually faster?

**Comment by fresheneesz** [comment]
"do you have any benchmark"

No, but its also easier to read, which I think is more important than the performance. There's no downside, only upsides.

```
x.indexOf(whatever) !== -1
vs
whatever in x
```

**Comment by slorber** [comment]
made release 1.1.1 
thanks

**Comment by fresheneesz** [comment]
Thanks!

**Pull request merged**
